name: pre-release push

on:
  push:
    branches: [ pre-release ]
env:
  DOTNET_NOLOGO: true                     
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true 
  DOTNET_CLI_TELEMETRY_OPTOUT: true  
  TF_BUILD: true   
jobs:
  build:
    runs-on: windows-latest
    name: "build and test"
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore RosSharp.sln
      - name: Build
        run: dotnet build --configuration Release --no-restore RosSharp.sln
      # - name: Test
      #   run: dotnet test --configuration Release --no-build --verbosity normal ./src
        
      - name: Publish opc client to NuGet
        continue-on-error: true
        uses: alirezanet/publish-nuget@v3.0.4
        with:
            PROJECT_FILE_PATH: RosBridgeClient/RosBridgeClient.ros.csproj
            NUGET_KEY: ${{secrets.NUGET_KEY}}
            VERSION_FILE_PATH: RosBridgeClient/RosBridgeClient.ros.csproj
            INCLUDE_SYMBOLS: true
            NO_BUILD: true

            
